[package]
name = "synchronous-traffic-light"
version = "1.0.0"
edition = "2024"

[dependencies]
eframe = "0.27.2"
egui = "0.27.2"

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
strip = true